#!/usr/bin/env bash
#
# installs g910-gkeys from pypi.org
#
VERSION=0.4.1
SUPPORTED_KEYBOARDS=(de en fr si)
UNIT_DIR=$(pkg-config systemd --variable=systemduserunitdir)
KEYBOARD=$(locale | grep LANG= | cut -d= -f2 | cut -d_ -f1)

[[ ! " ${SUPPORTED_KEYBOARDS[*]} " =~ ${KEYBOARD} ]] &&
	echo "Your system default language is $KEYBOARD, but it's not supported." &&
	echo "You can try to run: python3 cli_layout_config_helpers.py --create" &&
	echo "You need to add the created mapping to g910-gkeys.lib.data_mappers.char_uinput_mapper and" &&
	echo "add your locale to g910-gkeys.lib.data_mappers.supported_configs, before installing again." &&
	echo "The locale also have to be added to this install script 10:SUPPORTED_KEYBOARDS." &&
	echo "Please open a feature request on github with your language:" &&
	echo "https://github.com/JSubelj/g910-gkey-macro-support/issues/new/choose" &&
	exit 1

# install via pip
pip install g910-gkeys=="$VERSION"

# make config dir
if [[ ! -d "$HOME"/.config/g910-gkeys ]]; then
  mkdir "$HOME"/.config/g910-gkeys
fi

# check for existing config file
if [[ ! -f "$HOME"/.config/g910-gkeys/config.json ]]; then
  if [[ -f /etc/g910-gkeys/config.json ]]; then
    # if old config exist move it to new location (will need root privileges)
    sudo mv /etc/g910-gkeys/config.json "$HOME"/.config/g910-gkeys/config.json
    sudo chown "$USER":"$USER" "$HOME"/.config/g910-gkeys/config.json
  else
    # if not copy default config to config dir
    wget https://raw.githubusercontent.com/JSubelj/g910-gkey-macro-support/"$VERSION"/etc/config.json
    mv ./config.json "$HOME"/.config/g910-gkeys/config.json
  fi
fi

# copy service unit to systemd user unit dir
if [[ -d "$UNIT_DIR" ]]; then
  wget https://raw.githubusercontent.com/JSubelj/g910-gkey-macro-support/"$VERSION"/etc/g910-gkeys.service
  sudo mv ./g910-gkeys.service "$UNIT_DIR"/g910-gkeys.service
fi

# copy udev rules
if [[ ! -f /etc/udev/rules.d/60-g910-gkeys.rules ]]; then
  wget https://raw.githubusercontent.com/JSubelj/g910-gkey-macro-support/"$VERSION"/etc/60-g910-gkeys.rules
 sudo mv ./60-g910-gkeys.rules /etc/udev/rules.d/60-g910-gkeys.rules
fi

# enable uinput in kernel
if [[ ! -f /etc/modules-load.d/uinput-g910-gkeys.conf ]]; then
  wget https://raw.githubusercontent.com/JSubelj/g910-gkey-macro-support/"$VERSION"/etc/uinput-g910-gkeys.conf
  sudo mv ./uinput-g910-gkeys.conf /etc/modules-load.d/uinput-g910-gkeys.conf
fi

# reload daemon
systemctl --user daemon-reload

# enable and start service if necessary
systemctl --user enable --now g910-gkeys.service