[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "g910-gkeys"
version = "0.5.0"
authors = [
    { name="Jan Šubelj", email="jan.subelj010@gmail.com" },
    { name="Marcel Grolms", email="support@suabo.de" }
]
description = "Support for Logitech G910 GKeys on GNU/Linux"
keywords = ["logitech", "keyboard", "gkey", "G910", "G915", "G815", "G710", "G510"]
readme = "README.md"
requires-python = ">=3.12"
license-files = [ "LICENSE" ]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12"
]
dependencies = [
    "python-uinput==1.0.1",
    "hidapi==0.15.0",
]

[project.urls]
"Homepage" = "https://github.com/JSubelj/g910-gkey-macro-support"
"Bug Tracker" = "https://github.com/JSubelj/g910-gkey-macro-support/issues"

[project.scripts]
g910-gkeys = "g910_gkeys.g910_gkeys:main"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]
include = ["g910_gkeys*"]
exclude = ["g910_gkeys.tests*"]