NAME = 'g910-gkeys'
DESCRIPTION = 'Support for Logitech G910 GKeys on GNU/Linux'
URL = 'https://github.com/JSubelj/g910-gkey-macro-support'
EMAIL = 'jan.subelj010@gmail.com'
AUTHOR = 'Jan Šubelj'
REQUIRES_PYTHON = '>=3.7.0'
VERSION = '0.2.2'